# RuboCop configuration for Rails project
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'config/initializers/devise.rb'

# Style configurations
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Layout configurations
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'db/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics configurations
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

# Rails specific configurations
Rails/FilePath:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

# Performance configurations
Performance/StringReplacement:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

# Security configurations
Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true
