# Database configuration for different environments
# Rails uses different databases for development, test, and production

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dropshipping_store_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: dropshipping_store_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: dropshipping_store_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
